name: ğŸ› é”™è¯¯æŠ¥å‘Š | Bug report
description: Create a report to help us improve
title: "[Bug]"
labels:
  - bug
assignees: Oragekk
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |-
        Make SURE that you follow these statements.
      options:
        - label: I cloned this repository.
          required: true
          
        - label: I am using **LTS** version of Node.js.
          required: true

        - label: I am using the **latest v2 version** of VuePress and VuePress official plugins.
          required: true

        - label: I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
          required: true

        - label: I followed the docs and I double checked my configuration.
          required: true

        - label: I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.
          required: true

  - type: input
    id: package
    attributes:
      label: Package name
      description: Which package are you reporting
      value: vuepress-theme-hope
      placeholder: package name
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating system are you using?
      description: You may select more than one. Donâ€™t select anything if it's not about the environment.
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > If applicable, add screenshots and log to help explain your problem.(å¦‚æœé€‚ç”¨ï¼Œè¯·æ·»åŠ å±å¹•æˆªå›¾å’Œæ—¥å¿—ä»¥å¸®åŠ©è§£é‡Šä½ çš„é—®é¢˜ã€‚)

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.(æ¸…æ™°è€Œç®€æ˜åœ°æè¿°ä»€ä¹ˆæ˜¯é”™è¯¯ã€‚)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: If you are not reporting something obvious, a minimal reproduction repo and related log is required.(å¦‚æœæ‚¨æ²¡æœ‰æŠ¥å‘Šæ˜æ˜¾çš„å†…å®¹ï¼Œåˆ™éœ€è¦æœ€å°‘çš„å¯å¤ç°å­˜å‚¨åº“å’Œç›¸å…³æ—¥å¿—ã€‚)
      placeholder: Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuration.ï¼ˆåœ¨æ­¤å¤„æ·»åŠ æœ‰å…³è¯¥é—®é¢˜çš„ä»»ä½•å…¶ä»–ä¸Šä¸‹æ–‡ã€‚å°¤å…¶æ˜¯è¯¥é—®é¢˜å‘ç”Ÿåœ¨æŸäº›æ“ä½œç³»ç»Ÿã€æµè§ˆå™¨æˆ–é…ç½®ä¸­ã€‚ï¼‰
