name: 推送脚本

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
on:
  push:
    branches:
      - 'gh-pages'
    # paths:
    #   - 'sitemap.xml'

  schedule:
    - cron: "0 23 * * *" # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  push_bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: gh-pages

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # 设置缓存

      - name: 安装依赖
        run: |
          pip install -r main/requirements.txt

      - name: 运行脚本
        env:
          #设置secrets的环境变量
          BAIDU_KEY: ${{ secrets.BAIDU_KEY }}
          BING_KEY: ${{ secrets.BING_KEY }}
        run: |
          python main/script/submit.py --sitemap gh-pages/sitemap.xml
